### ISSUE TITLE
Неточность в README

### ISSUE THREAD

**Issue by shreddered** [bmstu-iu8-cpp-sem-3/lab-05-stack#4]
В [задании](https://github.com/bmstu-iu8-cpp-sem-3/lab-05-stack#задание-1) название класса _stack_ начинается с маленькой буквы. Если использовать предложенный стиль, код не пройдет проверки @rusdevops (проверки примут написанный шаблон класса за одноименный шаблон из STL и посоветуют добавить `#include <stack>`), что несколько сбивает с толку.

**Comment by rusdevops** [comment]
Пробовали добавить свой namespace ?

**Comment by shreddered** [comment]
Да, пробовал. Результат такой же - проверки не пройдены.

**Comment by shreddered** [comment]
Скорее всего, дело в том, что я использую реализацию `operator=` через метод swap (в некоторых источниках такую идиому называют _move and swap_). Я ~~безуспешно~~ пытался разными способами обойти эту ошибку.

Например, пытался сделать следующим образом:
```cpp
stack& operator=(stack&& other) noexcept {
    // ...
    stack(other).swap(*this);
    // ...
}
```
В этом случае `stack(other).swap(*this);` будет интерпретироваться как конструктор с одним параметром, то есть проверка завершится ошибкой и советом пометить найденный конструктор ключевым словом `explicit`.

Я попытался добавить свой namespace (код немного изменён, чтобы не спойлерить лабу):
```cpp
namespace lab05 {

template<typename T>
class stack {
public:
    // ...
    stack& operator=(stack&& other) noexcept {
        // ...
        // explicitly specified that I'm gonna use my own stack
        lab05::stack<T>(other).swap(*this);
        // ...
    }
    // ...
}; // class stack

} // namespace lab05
```
Результат - совет добавить `#include <stack>`
